### ISSUE TITLE
What is the difference between `last_updated` and `created`?

### ISSUE THREAD

**Issue by lgloege** [Open-Earth-Foundation/OpenClimate-data-ingestion#3]
Why do we need both of these variables if they are set to the same value. Should `last_updated` be when the dataset was last updated and `created` be when a particular record was created?  Maybe this issue is more appropriate for [OpenClimate-schema](https://github.com/Open-Earth-Foundation/OpenClimate-Schema/tree/0936c449778dc60a73591802a70a8c8ea3c79db1/SQL)

**Comment by evanp** [comment]
created is written once, last_updated is updated each time we, uh, update
